[package]
name          = "ataxia"
version       = "0.0.1-dev"
license       = "MIT/Apache-2.0"
authors       = ["Justin Seabrook-Rocha <xenith@xenith.org>"]
description   = """
A modern MUD engine using Lua for scripting and game logic
"""
homepage      = "https://github.com/xenith-studios/ataxia"
repository    = "https://github.com/xenith-studios/ataxia"
readme        = "README.md"
exclude       = [
  ".gitignore",
  "test/**/*",
]
build         = "build.rs"

[lib]
name = "ataxia"
path = "src/lib.rs"

#[[bin]]
#name = "ataxia-engine"
#path = "src/bin/ataxia-engine.rs"

#[[bin]]
#name = "ataxia-proxy"
#path = "src/bin/ataxia-proxy.rs"

[dependencies]
slog = "1.3.2"
slog-term = "1.3.3"
slog-stdlog = "1.1.0"
log = "0.3.6"
rand = "0.3.15"
toml = "0.2.1"
rustc-serialize = "0.3.21"
error-chain = "0.5"

[dependencies.clap]
version = "2.19.1"
default-features = false
features = [ "color", "wrap_help" ]

[build-dependencies]
time = "0.1.35"
