[package]
name          = "ataxia"
version       = "0.0.1-dev"
license       = "MIT/Apache-2.0"
authors       = ["Justin Seabrook-Rocha <xenith@xenith.org>"]
description   = """
A modern MUD engine using Lua for scripting and game logic
"""
homepage      = "https://github.com/xenith-studios/ataxia"
repository    = "https://github.com/xenith-studios/ataxia"
readme        = "README.md"
exclude       = [
  ".gitignore",
  "test/**/*",
]
build         = "build.rs"

#[lib]
#name = "ataxia_engine"
#path = "src/lib.rs"

[[bin]]
name = "ataxia"
path = "src/main.rs"

[[bin]]
name = "ataxia-proxy"
path = "src/proxy.rs"

[dependencies]
env_logger = "0.3.5"
log = "0.3.6"
rand = "0.3.14"
toml = "0.2.1"
rustc-serialize = "0.3.19"
error-chain = "0.5"

[dependencies.clap]
version = "2.12.1"
default-features = false
features = [ "color", "wrap_help" ]

[build-dependencies]
time = "0.1.35"
