[package]
name          = "ataxia"
version       = "0.0.1-dev"
license       = "MIT/Apache-2.0"
authors       = ["Justin Seabrook-Rocha <xenith@xenith.org>"]
description   = """
A modern MUD engine using Lua for scripting and game logic
"""
homepage      = "https://github.com/xenith-studios/ataxia"
repository    = "https://github.com/xenith-studios/ataxia"
readme        = "README.md"
exclude       = [
  ".gitignore",
  "test/**/*",
]
build         = "build.rs"

[lib]
name = "ataxia"
path = "src/lib.rs"

#[[bin]]
#name = "ataxia-engine"
#path = "src/bin/ataxia-engine.rs"

#[[bin]]
#name = "ataxia-proxy"
#path = "src/bin/ataxia-proxy.rs"

[dependencies]
slog = "^2.0"
slog-term = "^2.0.1"
rand = "^0.4"
toml = "^0.4"
serde = "^1.0"
serde_derive = "^1.0"
error-chain = "0.11.0-rc.2"

[dependencies.clap]
version = "2.19.1"
default-features = false
features = [ "color", "wrap_help" ]

[build-dependencies]
time = "0.1.35"
